### ISSUE TITLE
Revocability

### ISSUE THREAD

**Issue by lucaslokchan** [jamesbachini/Solidity-SBT-Soul-Bound-Token#1]
@jamesbachini Thanks for your awesome explanations and implementation of the paper.

In section 3 - Souls of the paper it states that:

> Our key primitive is accounts, or wallets, that hold publicly visible, non-transferable (but **possibly revocable-by-the-issuer**) tokens.

Could there be a mechanism for issuers to revoke SBTs from souls? Perhaps It is possible to accomplish this by including operator as msg.sender in the burn function.

```
function burn(address _soul) external {
        require(msg.sender == _soul || msg.sender == operator, "Only users and issuers have rights to delete their data");
        delete souls[_soul];
        for (uint i=0; i<profiles[_soul].length; i++) {
            address profiler = profiles[_soul][i];
            delete soulProfiles[profiler][_soul];
        }
        emit Burn(_soul);
    }
```

However, giving issuers the ability to revoke tokens removes some degree of decentralization; perhaps a voting or curator system could be implemented to make this more decentralized.

**Comment by jamesbachini** [comment]
Hi Lucas, Apologies for the delay in getting back to you, not sure how I missed this.

Yes that makes sense I've added it in. Thank you

**Comment by lucaslokchan** [comment]
👏
